<?php

/**
 * @file
 * Enables ding_readers_compass.
 */

include_once 'ding_readers_compass.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Tells panels where to find the .inc files that define various
 * args, contexts, content_types.
 */
function ding_readers_compass_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}
